.PHONY: clean All

All:
	@echo "----------Building project:[ MyWorkspace - Debug ]----------"
	@cd "MyWorkspace" && "$(MAKE)" -f  "MyWorkspace.mk"
clean:
	@echo "----------Cleaning project:[ MyWorkspace - Debug ]----------"
	@cd "MyWorkspace" && "$(MAKE)" -f  "MyWorkspace.mk" clean
