.PHONY: clean All

All:
	@echo "----------Building project:[ First_steps - Debug ]----------"
	@cd "First_steps" && "$(MAKE)" -f  "First_steps.mk"
clean:
	@echo "----------Cleaning project:[ First_steps - Debug ]----------"
	@cd "First_steps" && "$(MAKE)" -f  "First_steps.mk" clean
